FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive \
    RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:/opt/z3:/opt/boogie:$PATH

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    wget \
    unzip \
    git \
    build-essential \
    ca-certificates \
    cmake \
    ninja-build \
    g++-aarch64-linux-gnu \
    gcc-aarch64-linux-gnu \
    gcc-riscv64-linux-gnu \
    python3 \
    python3-pip \
    ruby-full \
    dotnet-sdk-8.0 \
    ghc \
    && rm -rf /var/lib/apt/lists/*
    
# Set default encoding to UTF-8
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

#Install z3 via pip
RUN pip install z3-solver

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Install boogie via dotnet
RUN dotnet tool install --tool-path /usr/local/bin boogie --version 3.5.4

# Install parallel gem
RUN gem install parallel
